import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { BarChart3, Bell, Box, ChevronLeft, CircleDollarSign, Cuboid, FileSpreadsheet, Home, LogOut, Menu, PackagePlus, Search, Settings, ShoppingBag, Trash2, TrendingUp, Users, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { useAuth } from '../contexts/AuthContext'
import { api } from '../lib/api'
import { categoryLabel, persianDate, toman } from '../lib/format'
import type { CustomerSummary, DashboardStats, Order, Product } from '../types'

type AdminView = 'overview' | 'products' | 'orders' | 'customers' | 'inventory' | 'reports' | 'settings'
const adminNav: Array<{ id: AdminView; label: string; icon: typeof Home }> = [
  { id: 'overview', label: 'داشبورد', icon: Home }, { id: 'products', label: 'محصولات', icon: Box }, { id: 'orders', label: 'سفارش‌ها', icon: ShoppingBag },
  { id: 'customers', label: 'مشتریان', icon: Users }, { id: 'inventory', label: 'موجودی و قیمت', icon: CircleDollarSign }, { id: 'reports', label: 'گزارش‌ها', icon: BarChart3 }, { id: 'settings', label: 'تنظیمات', icon: Settings },
]

export function AdminDashboardPage() {
  const [view, setView] = useState<AdminView>('overview'); const [mobileOpen, setMobileOpen] = useState(false)
  const [stats, setStats] = useState<DashboardStats | null>(null); const [orders, setOrders] = useState<Order[]>([])
  const [products, setProducts] = useState<Product[]>([]); const [customers, setCustomers] = useState<CustomerSummary[]>([])
  const [modal, setModal] = useState(false); const { user, logout } = useAuth(); const navigate = useNavigate()
  const load = useCallback(async () => { const [nextStats, nextOrders, nextProducts, nextCustomers] = await Promise.all([api.adminStats(), api.adminOrders(), api.products(), api.customers()]); setStats(nextStats); setOrders(nextOrders); setProducts(nextProducts); setCustomers(nextCustomers) }, [])
  useEffect(() => { load() }, [load])
  const logoutNow = () => { logout(); navigate('/login') }
  const selectView = (next: AdminView) => { setView(next); setMobileOpen(false) }
  return <div className="admin-dashboard" dir="rtl"><aside className={`admin-sidebar ${mobileOpen ? 'is-open' : ''}`}><button className="admin-close" onClick={() => setMobileOpen(false)}><X /></button><Brand light /><nav>{adminNav.map(item => <button key={item.id} className={view === item.id ? 'active' : ''} onClick={() => selectView(item.id)}><item.icon /><span>{item.label}</span>{item.id === 'orders' && stats?.newOrders ? <small>{new Intl.NumberFormat('fa-IR').format(stats.newOrders)}</small> : null}</button>)}</nav><button className="logout-link" onClick={logoutNow}><LogOut /> خروج</button></aside><div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu" onClick={() => setMobileOpen(true)}><Menu /></button><div><button className="icon-button"><Bell /></button><span><b>{user?.fullName}</b><small>مدیر کل</small></span></div><button className="button button--emerald" onClick={() => setModal(true)}><PackagePlus /> افزودن محصول</button></header><main className="admin-main">
    {view === 'overview' ? <AdminOverview stats={stats} orders={orders} onOrders={() => setView('orders')} /> : null}
    {view === 'products' ? <ProductsView products={products} reload={load} onAdd={() => setModal(true)} /> : null}
    {view === 'orders' ? <OrdersView orders={orders} reload={load} /> : null}
    {view === 'customers' ? <CustomersView customers={customers} /> : null}
    {view === 'inventory' ? <InventoryView stats={stats} products={products} /> : null}
    {view === 'reports' ? <ReportsView stats={stats} orders={orders} /> : null}
    {view === 'settings' ? <SettingsView /> : null}
  </main></div>{modal ? <ProductModal onClose={() => setModal(false)} onSaved={async () => { setModal(false); await load(); setView('products') }} /> : null}</div>
}

function AdminOverview({ stats, orders, onOrders }: { stats: DashboardStats | null; orders: Order[]; onOrders: () => void }) {
  const metrics = [{ label: 'فروش امروز', value: toman(stats?.salesToday ?? 0), icon: TrendingUp, tone: 'green' }, { label: 'سفارش‌های جدید', value: `${new Intl.NumberFormat('fa-IR').format(stats?.newOrders ?? 0)} سفارش`, icon: ShoppingBag, tone: 'blue' }, { label: 'محصولات کم‌موجود', value: `${new Intl.NumberFormat('fa-IR').format(stats?.lowStock ?? 0)} محصول`, icon: Cuboid, tone: 'gold' }, { label: 'مشتریان فعال', value: `${new Intl.NumberFormat('fa-IR').format(stats?.activeCustomers ?? 0)} نفر`, icon: Users, tone: 'silver' }]
  return <><div className="admin-page-heading"><div><h1>داشبورد مدیریت</h1><p>خلاصه وضعیت امروز فروشگاه مبین سیلور</p></div><span>{new Intl.DateTimeFormat('fa-IR', { dateStyle: 'full' }).format(new Date())}</span></div><div className="metric-row">{metrics.map(metric => <div className="metric" key={metric.label}><span className={`metric__icon metric__icon--${metric.tone}`}><metric.icon /></span><div><small>{metric.label}</small><strong>{metric.value}</strong><em>به‌روزرسانی لحظه‌ای</em></div></div>)}</div><div className="admin-overview-grid"><section className="admin-panel sales-chart"><div className="admin-panel__title"><h2>روند فروش هفتگی</h2><span>۷ روز اخیر</span></div><SalesChart values={stats?.chart.map(x => x.total) ?? []} /></section><section className="admin-panel metals-panel"><div className="admin-panel__title"><h2>قیمت و موجودی فلزات</h2></div><MetalRow name="نقره ۹۹۹" price={stats?.silverPrice ?? 0} stock="۱۲٬۴۵۰ گرم" tone="silver" /><MetalRow name="طلا ۹۹۹٫۹" price={stats?.goldPrice ?? 0} stock="۲٬۳۳۵ گرم" tone="gold" /></section></div><section className="admin-panel admin-orders-preview"><div className="admin-panel__title"><h2>سفارش‌های اخیر</h2><div className="admin-search"><Search /><input placeholder="جستجوی سفارش..." /></div></div><OrdersTable orders={orders.slice(0, 5)} /><button className="panel-link" onClick={onOrders}>مشاهده همه سفارش‌ها <ChevronLeft /></button></section></>
}

function SalesChart({ values }: { values: number[] }) {
  const normalized = values.length ? values : [20, 38, 55, 42, 72, 83, 100]
  const max = Math.max(...normalized, 1); const points = normalized.map((value, index) => `${index * (600 / Math.max(1, normalized.length - 1))},${170 - (value / max) * 135}`).join(' ')
  return <div className="chart-wrap"><svg viewBox="0 0 600 200" role="img" aria-label="نمودار فروش هفتگی"><defs><linearGradient id="chart-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#0e6a58" stopOpacity=".28" /><stop offset="1" stopColor="#0e6a58" stopOpacity="0" /></linearGradient></defs>{[35, 80, 125, 170].map(y => <line key={y} x1="0" x2="600" y1={y} y2={y} className="chart-grid" />)}<polygon points={`0,180 ${points} 600,180`} fill="url(#chart-fill)" /><polyline points={points} className="chart-line" />{normalized.map((value, index) => <circle key={index} cx={index * (600 / Math.max(1, normalized.length - 1))} cy={170 - (value / max) * 135} r="5" />)}</svg><div className="chart-labels">{['پنجشنبه', 'جمعه', 'شنبه', 'یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه'].map(day => <span key={day}>{day}</span>)}</div></div>
}
function MetalRow({ name, price, stock, tone }: { name: string; price: number; stock: string; tone: string }) { return <div className="metal-row"><span className={`metal-dot metal-dot--${tone}`}><Cuboid /></span><div><b>{name}</b><small>قیمت هر گرم</small></div><strong>{toman(price)}</strong><div><b>{stock}</b><small>موجودی قابل فروش</small></div></div> }

function ProductsView({ products, reload, onAdd }: { products: Product[]; reload: () => Promise<void>; onAdd: () => void }) {
  const [query, setQuery] = useState(''); const shown = useMemo(() => products.filter(x => x.name.includes(query)), [products, query])
  const remove = async (id: number) => { if (!window.confirm('این محصول حذف شود؟')) return; await api.deleteProduct(id); await reload() }
  return <section><AdminSectionTitle title="مدیریت محصولات" copy="محصولات، قیمت و موجودی فروشگاه" action={<button className="button button--emerald" onClick={onAdd}><PackagePlus /> افزودن محصول</button>} /><div className="admin-panel table-panel"><div className="table-toolbar"><div className="admin-search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="جستجوی محصول..." /></div><span>{new Intl.NumberFormat('fa-IR').format(shown.length)} محصول</span></div><div className="responsive-table"><table><thead><tr><th>محصول</th><th>دسته‌بندی</th><th>قیمت</th><th>موجودی</th><th>عیار</th><th>عملیات</th></tr></thead><tbody>{shown.map(product => <tr key={product.id}><td><div className="table-product"><img src={product.imageUrl} alt="" /><span><b>{product.name}</b><small>{product.weight}</small></span></div></td><td>{categoryLabel[product.category]}</td><td>{toman(product.price)}</td><td><span className={product.stock <= 5 ? 'stock-low' : ''}>{new Intl.NumberFormat('fa-IR').format(product.stock)} عدد</span></td><td>{product.purity}</td><td><button className="table-delete" onClick={() => remove(product.id)}><Trash2 /> حذف</button></td></tr>)}</tbody></table></div></div></section>
}

function OrdersView({ orders, reload }: { orders: Order[]; reload: () => Promise<void> }) {
  const [busy, setBusy] = useState<number | null>(null); const update = async (id: number, status: string) => { setBusy(id); await api.updateOrderStatus(id, status); await reload(); setBusy(null) }
  return <section><AdminSectionTitle title="سفارش‌ها" copy="بررسی و مدیریت وضعیت سفارش‌های مشتریان" /><div className="admin-panel table-panel"><div className="responsive-table"><table><thead><tr><th>شماره سفارش</th><th>مشتری</th><th>تاریخ</th><th>مبلغ</th><th>تعداد کالا</th><th>وضعیت</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td><b>{order.orderNumber}</b></td><td><span>{order.customerName}</span><small className="block">{order.phone}</small></td><td>{persianDate(order.createdAt)}</td><td>{toman(order.total)}</td><td>{new Intl.NumberFormat('fa-IR').format(order.items.reduce((sum, x) => sum + x.quantity, 0))}</td><td><select className="status-select" value={order.status} disabled={busy === order.id} onChange={e => update(order.id, e.target.value)}><option>در انتظار بررسی</option><option>پرداخت شده</option><option>در حال آماده‌سازی</option><option>ارسال شده</option><option>تحویل شده</option><option>لغو شده</option></select></td></tr>)}</tbody></table></div></div></section>
}

function CustomersView({ customers }: { customers: CustomerSummary[] }) { return <section><AdminSectionTitle title="مشتریان" copy="فهرست حساب‌های ثبت‌شده در فروشگاه" /><div className="admin-panel table-panel"><div className="responsive-table"><table><thead><tr><th>مشتری</th><th>ایمیل</th><th>موبایل</th><th>تاریخ عضویت</th><th>سفارش‌ها</th></tr></thead><tbody>{customers.map(customer => <tr key={customer.id}><td><b>{customer.fullName}</b></td><td>{customer.email}</td><td>{customer.phone || '—'}</td><td>{persianDate(customer.createdAt)}</td><td>{new Intl.NumberFormat('fa-IR').format(customer.orders)} سفارش</td></tr>)}</tbody></table></div></div></section> }

function InventoryView({ stats, products }: { stats: DashboardStats | null; products: Product[] }) { return <section><AdminSectionTitle title="موجودی و قیمت" copy="پایش موجودی کالا و مرجع قیمت فلزات" /><div className="inventory-prices"><MetalRow name="نقره ۹۹۹" price={stats?.silverPrice ?? 0} stock="۱۲٬۴۵۰ گرم" tone="silver" /><MetalRow name="طلا ۹۹۹٫۹" price={stats?.goldPrice ?? 0} stock="۲٬۳۳۵ گرم" tone="gold" /></div><div className="admin-panel table-panel"><div className="responsive-table"><table><thead><tr><th>محصول</th><th>وزن</th><th>قیمت فروش</th><th>موجودی</th><th>وضعیت</th></tr></thead><tbody>{products.map(product => <tr key={product.id}><td><b>{product.name}</b></td><td>{product.weight}</td><td>{toman(product.price)}</td><td>{new Intl.NumberFormat('fa-IR').format(product.stock)}</td><td><span className={`status status--${product.stock <= 5 ? 'warning' : 'success'}`}>{product.stock <= 5 ? 'نیاز به تأمین' : 'موجود'}</span></td></tr>)}</tbody></table></div></div></section> }

function ReportsView({ stats, orders }: { stats: DashboardStats | null; orders: Order[] }) { const total = orders.reduce((sum, x) => sum + x.total, 0); return <section><AdminSectionTitle title="گزارش‌ها" copy="نمای کلی عملکرد فروش و سفارش‌ها" action={<button className="button button--outline"><FileSpreadsheet /> خروجی اکسل</button>} /><div className="report-cards"><div><small>فروش کل</small><strong>{toman(total)}</strong><TrendingUp /></div><div><small>میانگین سفارش</small><strong>{toman(orders.length ? total / orders.length : 0)}</strong><CircleDollarSign /></div><div><small>تعداد سفارش‌ها</small><strong>{new Intl.NumberFormat('fa-IR').format(orders.length)}</strong><ShoppingBag /></div></div><section className="admin-panel sales-chart"><div className="admin-panel__title"><h2>فروش هفتگی</h2></div><SalesChart values={stats?.chart.map(x => x.total) ?? []} /></section></section> }

function SettingsView() { const [saved, setSaved] = useState(false); return <section><AdminSectionTitle title="تنظیمات فروشگاه" copy="اطلاعات عمومی و تنظیمات سفارش" /><form className="admin-panel settings-form" onSubmit={e => { e.preventDefault(); setSaved(true) }}><label><span>نام فروشگاه</span><input defaultValue="مبین سیلور" /></label><label><span>شماره پشتیبانی</span><input defaultValue="۰۲۱-۹۱۰۰۰۰۰۰" /></label><label className="full"><span>پیام بالای فروشگاه</span><input defaultValue="بسم الله الرحمن الرحیم • إِنَّا فَتَحْنَا لَكَ فَتْحًا مُبِينًا" /></label><label className="check-line"><input type="checkbox" defaultChecked /> ارسال پیامک پس از تغییر وضعیت سفارش</label><button className="button button--emerald">ذخیره تنظیمات</button>{saved ? <span className="save-message">تنظیمات ذخیره شد.</span> : null}</form></section> }

function OrdersTable({ orders }: { orders: Order[] }) { return <div className="responsive-table"><table><thead><tr><th>شماره سفارش</th><th>مشتری</th><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td><b>{order.orderNumber}</b></td><td>{order.customerName}</td><td>{toman(order.total)}</td><td><span className={`status status--${order.status.includes('ارسال') ? 'success' : 'warning'}`}>{order.status}</span></td><td>{persianDate(order.createdAt)}</td></tr>)}</tbody></table></div> }
function AdminSectionTitle({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="admin-page-heading"><div><h1>{title}</h1><p>{copy}</p></div>{action}</div> }

function ProductModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState({ name: '', slug: '', category: 'silver-bar', description: '', price: 0, imageUrl: '/assets/silver-bar.png', stock: 1, purity: '۹۹۹', weight: '۱ اونس', featured: false }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await api.createProduct(form as Omit<Product, 'id' | 'createdAt'>); await onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'ذخیره انجام نشد.') } finally { setSaving(false) } }
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="product-modal-title"><div className="modal__header"><div><h2 id="product-modal-title">افزودن محصول</h2><p>اطلاعات محصول جدید را وارد کنید.</p></div><button onClick={onClose}><X /></button></div><form onSubmit={submit}><div className="form-grid"><label><span>نام محصول</span><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label><span>نامک انگلیسی</span><input required dir="ltr" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></label><label><span>دسته‌بندی</span><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value, imageUrl: e.target.value === 'gold-bar' ? '/assets/gold-bar.png' : e.target.value === 'silver-jewelry' ? '/assets/silver-ring.png' : '/assets/silver-bar.png' })}><option value="silver-bar">شمش نقره</option><option value="silver-jewelry">زیورآلات نقره</option><option value="gold-bar">شمش طلا</option></select></label><label><span>قیمت (تومان)</span><input required type="number" min="1" value={form.price || ''} onChange={e => setForm({ ...form, price: Number(e.target.value) })} /></label><label><span>موجودی</span><input required type="number" min="0" value={form.stock} onChange={e => setForm({ ...form, stock: Number(e.target.value) })} /></label><label><span>وزن</span><input required value={form.weight} onChange={e => setForm({ ...form, weight: e.target.value })} /></label><label><span>عیار</span><input required value={form.purity} onChange={e => setForm({ ...form, purity: e.target.value })} /></label><label className="check-line"><input type="checkbox" checked={form.featured} onChange={e => setForm({ ...form, featured: e.target.checked })} /> نمایش در منتخب مبین</label><label className="full"><span>توضیحات</span><textarea required rows={3} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label></div>{error ? <div className="form-error">{error}</div> : null}<div className="modal__actions"><button type="button" className="button button--outline" onClick={onClose}>انصراف</button><button className="button button--emerald" disabled={saving}>{saving ? 'در حال ذخیره...' : 'ذخیره محصول'}</button></div></form></div></div>
}
