import { useState, type FormEvent } from 'react'
import { Eye, EyeOff, LockKeyhole, UserRound } from 'lucide-react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { useAuth } from '../contexts/AuthContext'

export function LoginPage() {
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [visible, setVisible] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [form, setForm] = useState({ username: '', password: '', fullName: '', phone: '' })
  const [error, setError] = useState('')
  const { user, login, register, loading } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  if (loading && !submitting) return <div className="route-loading" role="status"><span /> در حال بررسی نشست...</div>
  if (user && !submitting) return <Navigate to={user.role === 'Admin' ? '/admin' : '/dashboard'} replace />
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setSubmitting(true); const requested = (location.state as { from?: string } | null)?.from; try { const next = mode === 'login' ? await login(form.username, form.password) : await register({ fullName: form.fullName, email: form.username, password: form.password, phone: form.phone }); navigate(next.role === 'Admin' ? '/admin' : requested ?? '/dashboard', { replace: true }) } catch (e) { setError(e instanceof Error ? e.message : 'ورود انجام نشد.'); setSubmitting(false) } }
  return <section className="auth-page"><div className="auth-visual"><Brand light /><div><h1>فلزات ارزشمند،<br />انتخابی ماندگار</h1><p>به حساب مبین سیلور وارد شوید و سفارش‌ها، نشانی و علاقه‌مندی‌های خود را مدیریت کنید.</p></div><small>مبین سیلور؛ همراه مطمئن سرمایه و زیبایی</small></div><div className="auth-form-wrap"><div className="auth-form"><UserRound className="auth-form__icon" /><h2>{mode === 'login' ? 'ورود به حساب کاربری' : 'ساخت حساب جدید'}</h2><p>{mode === 'login' ? 'نام کاربری یا ایمیل و رمز عبور را وارد کنید.' : 'برای شروع خرید، اطلاعات زیر را تکمیل کنید.'}</p><div className="auth-tabs"><button type="button" className={mode === 'login' ? 'active' : ''} onClick={() => { setMode('login'); setError('') }}>ورود</button><button type="button" className={mode === 'register' ? 'active' : ''} onClick={() => { setMode('register'); setError('') }}>ثبت‌نام</button></div><form onSubmit={submit}>{mode === 'register' ? <><label><span>نام و نام خانوادگی</span><input autoComplete="name" required minLength={3} value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} /></label><label><span>شماره موبایل</span><input autoComplete="tel" inputMode="tel" pattern="09[0-9]{9}" required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label></> : null}<label><span>{mode === 'login' ? 'نام کاربری یا ایمیل' : 'ایمیل'}</span><input autoFocus autoComplete="username" type={mode === 'register' ? 'email' : 'text'} required value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></label><label><span>رمز عبور</span><div className="password-input"><LockKeyhole /><input autoComplete={mode === 'login' ? 'current-password' : 'new-password'} required minLength={mode === 'register' ? 8 : 1} type={visible ? 'text' : 'password'} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><button type="button" onClick={() => setVisible(v => !v)} aria-label={visible ? 'پنهان کردن رمز' : 'نمایش رمز'}>{visible ? <EyeOff /> : <Eye />}</button></div></label>{error ? <div className="form-error" role="alert">{error}</div> : null}<button className="button button--emerald button--full" disabled={loading || submitting}>{loading || submitting ? 'لطفاً صبر کنید...' : mode === 'login' ? 'ورود به حساب' : 'ایجاد حساب'}</button></form><div className="auth-security-note"><LockKeyhole /> اطلاعات ورود شما رمزنگاری‌شده منتقل می‌شود.</div></div></div></section>
}
