import { useState, type FormEvent } from 'react'
import { Eye, EyeOff, LockKeyhole, UserRound } from 'lucide-react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { useAuth } from '../contexts/AuthContext'

export function LoginPage() {
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [visible, setVisible] = useState(false)
  const [form, setForm] = useState({ username: '', password: '', fullName: '', phone: '' })
  const [error, setError] = useState('')
  const { user, login, register, loading } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  if (user) return <Navigate to={user.role === 'Admin' ? '/admin' : '/dashboard'} replace />
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const next = mode === 'login' ? await login(form.username, form.password) : await register({ fullName: form.fullName, email: form.username, password: form.password, phone: form.phone }); const requested = (location.state as { from?: string } | null)?.from; navigate(next.role === 'Admin' ? '/admin' : requested ?? '/dashboard', { replace: true }) } catch (e) { setError(e instanceof Error ? e.message : 'ورود انجام نشد.') } }
  return <section className="auth-page"><div className="auth-visual"><Brand light /><div><h1>فلزات ارزشمند،<br />انتخابی ماندگار</h1><p>به حساب مبین سیلور وارد شوید و سفارش‌ها، نشانی‌ها و علاقه‌مندی‌های خود را مدیریت کنید.</p></div><small>مبین سیلور؛ همراه مطمئن سرمایه و زیبایی</small></div><div className="auth-form-wrap"><div className="auth-form"><UserRound className="auth-form__icon" /><h2>{mode === 'login' ? 'ورود به حساب کاربری' : 'ساخت حساب جدید'}</h2><p>{mode === 'login' ? 'نام کاربری یا ایمیل و رمز عبور را وارد کنید.' : 'برای شروع خرید، اطلاعات زیر را تکمیل کنید.'}</p><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>ورود</button><button className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>ثبت‌نام</button></div><form onSubmit={submit}>{mode === 'register' ? <><label><span>نام و نام خانوادگی</span><input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} /></label><label><span>شماره موبایل</span><input required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label></> : null}<label><span>{mode === 'login' ? 'نام کاربری یا ایمیل' : 'ایمیل'}</span><input autoFocus required value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></label><label><span>رمز عبور</span><div className="password-input"><LockKeyhole /><input required minLength={6} type={visible ? 'text' : 'password'} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><button type="button" onClick={() => setVisible(v => !v)} aria-label="نمایش رمز">{visible ? <EyeOff /> : <Eye />}</button></div></label>{error ? <div className="form-error">{error}</div> : null}<button className="button button--emerald button--full" disabled={loading}>{loading ? 'لطفاً صبر کنید...' : mode === 'login' ? 'ورود به حساب' : 'ایجاد حساب'}</button></form>{mode === 'login' ? <div className="demo-hint"><b>ورود مدیر فروشگاه</b><span>نام کاربری: admin</span><span>رمز عبور: admin123</span></div> : null}</div></div></section>
}
